---
output:
  word_document: default
  html_document: default
---


```{r library, message=FALSE}
options(tidyverse.quiet = TRUE)

library(tidyverse)
library(MASS)
library(caret)
library(GGally)
```



```{r Task 1, message=FALSE}

library(tidyverse)
library(tidyquant)



hour <- read_csv("hour.csv")
bike = as_tibble(hour)

bike = bike %>% mutate(season = as_factor(as.character(season))) %>%
mutate(season = fct_recode(season,
"Spring" = "1",
"Summer" = "2",
"Fall" = "3",
"Winter" = "4"))

bike = bike %>% mutate(yr = as_factor(as.character(yr))) %>%
mutate(yr = fct_recode(yr,
"0" = "0",
"1" = "1"))


# We decided to convert yr, mnth and hr variables into factors to convert them to categorical variables. 
# These values are not logically quantitative. Even though they are numbers they represent a categorical/string value. 
# We should not be running models on "Tuesday". 

bike = bike %>% mutate(mnth = as_factor(as.character(mnth))) %>%
mutate(mnth = fct_recode(mnth,
"1" = "1",
"2" = "2",
"3" = "3",
"4" = "4",
"5" = "5",
"6" = "6",
"7" = "7",
"8" = "8",
"9" = "9",
"10" = "10",
"11" = "11",
"12" = "12"))

bike = bike %>% mutate(hr = as_factor(as.character(hr))) %>%
mutate(hr = fct_recode(hr,
"0" = "0",
"1" = "1",
"2" = "2",
"3" = "3",
"4" = "4",
"5" = "5",
"6" = "6",
"7" = "7",
"8" = "8",
"9" = "9",
"10" = "10",
"11" = "11",
"12" = "12",
"13" = "13",
"14" = "14",
"15" = "15",
"16" = "16",
"17" = "17",
"18" = "18",
"19" = "19",
"20" = "20",
"21" = "21",
"22" = "22",
"23" = "23"))

bike = bike %>% mutate(holiday = as_factor(as.character(holiday))) %>%
mutate(holiday = fct_recode(holiday,
"NotHoliday" = "0",
"Holiday" = "1"))

bike = bike %>% mutate(workingday = as_factor(as.character(workingday))) %>%
mutate(workingday = fct_recode(workingday,
"NotWorkingDay" = "0",
"WorkingDay" = "1"))

bike = bike %>% mutate(weathersit = as_factor(as.character(weathersit))) %>%
mutate(weathersit = fct_recode(weathersit,
"NoPrecip" = "1",
"Misty" = "2",
"LightPrecip" = "3",
"HeavyPrecip" = "4"))

bike = bike %>% mutate(weekday = as_factor(as.character(weekday))) %>%
mutate(weekday = fct_recode(weekday,
"Sunday" = "0",
"Monday" = "1",
"Tuesday" = "2",
"Wednesday" = "3", 
"Thursday" = "4",
"Friday" = "5",
"Saturday" = "6"))

bike = bike %>% drop_na() #drops N/A's
str(bike)
```


```{r Task 2, message=FALSE}
set.seed(1234)
train.rows = createDataPartition(y = bike$count, p = 0.7, list =FALSE)
train = slice(bike, train.rows)
test = slice(bike, -train.rows)

```


```{r Task 3}

mod1 = lm(count ~ season + mnth + hr + holiday + weekday + temp + weathersit, train)
summary(mod1)


```


```{r Task 4}

train_pred = predict(mod1, newdata = train)

SSE = sum((train$count - train_pred)^2)
SST = sum((train$count - mean(train$count))^2)
1 - SSE/SST

summary(train_pred)

head(train_pred)

ggplot(train,aes(x=train_pred)) + geom_histogram() + labs(title = "Train Prediction")

```


```{r Task 5}

predict_test = predict(mod1, newdata = test)
summary(predict_test)

ggplot(test, aes(x=predict_test)) + geom_histogram() + labs(title = "Test Prediction")

```



```{r Task 6}

SSE = sum((test$count - predict_test)^2)
SST = sum((test$count - mean(test$count))^2)
1 - SSE/SST

```






```{r Task 7}
ggcorr(bike)#Determining what variables are most correlated with Count

ctrl = trainControl(method = "cv", number = 10)

set.seed(123)
modCV = train(count ~ registered, bike, method = "lm", trControl = ctrl, metric = "Rsquared")
summary(modCV)

```

